FROM alpine:3.14
RUN apk add \
  nginx \
  php7-common \
  php7 \
  php7-fpm \
  php7-gd \
  php7-mbstring \
  php7-pdo \
  php7-sqlite3 \
  php7-json \
  php7-ctype \
  php7-curl \
  php7-dom \
  php7-intl \
  php7-openssl \ 
  php7-mysqlnd \
  php7-mysqli \
  php7-opcache \
  php7-phar \
  php7-session \
  php7-xml \
  php7-xmlreader \
  php7-pdo_sqlite \
  php7-zip \
  supervisor

RUN rm -f /etc/nginx/http.d/*
COPY conf/showdoc.conf /etc/nginx/http.d/
COPY conf/supervisord.conf /etc/supervisord.conf
COPY --chown=nobody:nobody ./  /var/www/html/
RUN rm -rf /var/www/html/conf

CMD ["/usr/bin/supervisord","-c","/etc/supervisord.conf"]